In [1]:
import numpy as np
import pickle
import pandas as pd

In [2]:
eval = pd.read_csv('/home/fernandi/projects/decision-diffuser/code/skills/dif.csv')

In [5]:
#sort eval by diff_x and diff_y
eval = eval.sort_values(by=['diff_x','diff_y'])
eval.tail(100)

rigth_w  up_w     diff_x    diff_y
7736      7.7   3.6  13.490059 -1.736719
7823      7.8   2.3  13.490059 -1.698503
7857      7.8   5.7  13.490059 -1.686919
8753      8.7   5.3  13.490059 -1.649463
8427      8.4   2.7  13.490059 -1.533215
...       ...   ...        ...       ...
8129      8.1   2.9  13.490059  0.819603
8598      8.5   9.8  13.490059  0.821604
8499      8.4   9.9  13.490059  0.880206
8016      8.0   1.6  13.490059  1.093154
8724      8.7   2.4  13.490059  1.199049

[100 rows x 4 columns]

In [ ]:
#conver pickle to csv
import pandas as pd
import numpy as np
import pickle

with open('/home/fernandi/projects/decision-diffuser/code/trajectories/safe_grid_2000_0_noise.pickle','rb') as f:
    data = pickle.load(f)

df = pd.DataFrame(data['observations'])
df['action_x'] = data['actions'][:,0]
df['action_y'] = data['actions'][:,1]
df['rewards'] = data['rewards']
df['terminals'] = data['terminals']
df["costs"] = data["costs"]
df.to_csv('/home/fernandi/projects/decision-diffuser/code/trajectories/safe_grid_2000_0_noise.csv')

In [1]:
import pickle

In [16]:
#load pickle file
with open('/home/fernandi/projects/decision-diffuser/code/trajectories/safe_grid_2000_0_noise.pickle','rb') as f:
    data = pickle.load(f)
print(data.keys())
print(data['observations'].shape)
print(data['actions'].shape)
print(data['rewards'].shape)
print(data['terminals'].shape)
print(data['observations'][0])
print(data['actions'][0])
print(data['rewards'][0])
print(data['terminals'][0])

dict_keys(['observations', 'actions', 'rewards', 'costs', 'terminals'])
(33251, 14)
(33251, 2)
(33251,)
(33251,)
[  0.91984232   1.63093368  12.15331973  14.6298702    5.29134147
  15.57711582  14.47761887  42.142167    13.97782604 349.01206464
  19.41604426  15.57711582  12.34870579  15.57711582]
[0.79226244 0.67522289]
1.0295972526376111
False


In [17]:
#get terminal index where terminal = 1
import numpy as np
terminals = data['terminals']
terminals = np.where(terminals == 1)
terminals = terminals[0]
print(terminals)


[   16    40    59 ... 33209 33230 33250]


In [18]:
prev_terminal = 0
acc_rewards = []
acc_costs = []
for i in range(2000):
    acc_rewards.append(np.sum(data['rewards'][prev_terminal:terminals[i]]))
    acc_costs.append(np.sum(data['costs'][prev_terminal:terminals[i]]))
    prev_terminal = terminals[i]

print(f"acc_rewards: {np.array(acc_rewards).mean()}")
print(f"acc_costs: {np.array(acc_costs).mean()}")

acc_rewards: 22.48068015393375
acc_costs: 2.4243519134879765


In [19]:
print(np.array(acc_rewards).max())
print(np.array(acc_costs).max())

37.3378031531394
18.878305620840987


In [ ]:
data["rewards"][episode_start:episode_end] 

array([-15.6024354 , -15.32056707, -14.94486791, -15.46089436,
       -14.79110776, -14.09009524, -13.42701378, -13.34837588,
       -13.45699295, -12.83555064, -12.26425951, -11.75043669,
       -11.70711084, -11.26489418, -10.89675354, -10.6769362 ,
       -10.49288961, -10.35238762, -10.3531313 , -10.47555408])

In [69]:
data['terminals'][episode_start:episode_end]

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True])

In [70]:
data['rewards'][episode_start:episode_end]

array([-15.6024354 , -15.32056707, -14.94486791, -15.46089436,
       -14.79110776, -14.09009524, -13.42701378, -13.34837588,
       -13.45699295, -12.83555064, -12.26425951, -11.75043669,
       -11.70711084, -11.26489418, -10.89675354, -10.6769362 ,
       -10.49288961, -10.35238762, -10.3531313 , -10.47555408])

In [76]:
episode_observations =data['observations'][episode_start:episode_end]
episode_actions =data['actions'][episode_start:episode_end]
#loop through the episode
for i in range(episode_observations.shape[0]):
    print(f"Observation: {episode_observations[i]}")
    print(f"Action: {episode_actions[i]}")
    print(f:"Reward: {data['rewards'][episode_start+i]}")
    print("==================================================")

array([[ 8.62523449,  0.6856116 , 11.55766122, 19.06800662],
       [ 9.62523449,  0.6856116 , 11.55766122, 19.06800662],
       [ 8.87299606,  0.6856116 , 11.55766122, 19.06800662],
       [ 8.06169808,  0.6856116 , 11.55766122, 19.06800662],
       [ 0.80071501,  4.34836355, 12.3312694 , 14.64048858],
       [ 0.60488237,  4.34836355, 12.3312694 , 14.64048858],
       [ 0.98261584,  4.34836355, 12.3312694 , 14.64048858],
       [ 1.49516128,  4.34836355, 12.3312694 , 14.64048858],
       [ 0.79387728,  4.34836355, 12.3312694 , 14.64048858],
       [ 1.70822693,  4.34836355, 12.3312694 , 14.64048858],
       [ 2.70822693,  4.34836355, 12.3312694 , 14.64048858],
       [ 3.70822693,  4.34836355, 12.3312694 , 14.64048858],
       [ 3.83119288,  4.34836355, 12.3312694 , 14.64048858],
       [ 3.66161995,  4.34836355, 12.3312694 , 14.64048858],
       [ 4.66161995,  4.34836355, 12.3312694 , 14.64048858],
       [ 5.66161995,  4.34836355, 12.3312694 , 14.64048858],
       [ 6.66161995,  4.

In [72]:
first_episode[:,2:4][0]

array([11.55766122, 19.06800662])

In [77]:
data['actions'][episode_start:episode_end]

array([[-0.19583264,  0.        ],
       [ 0.37773347,  0.        ],
       [ 0.51254544,  0.        ],
       [-0.70128399,  0.        ],
       [ 0.91434965,  0.        ],
       [ 1.        ,  0.        ],
       [ 1.        ,  0.        ],
       [ 0.12296595,  0.        ],
       [-0.16957292,  0.        ],
       [ 1.        ,  0.        ],
       [ 1.        ,  0.        ],
       [ 1.        ,  0.        ],
       [ 0.09034783,  0.        ],
       [ 1.        ,  0.        ],
       [ 1.        ,  0.        ],
       [ 0.73868039,  0.        ],
       [ 0.7978548 ,  0.        ],
       [ 0.92737785,  0.        ],
       [-0.00688146,  0.        ],
       [-0.82949727,  0.        ]])